// <auto-generated />
using System;
using DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DAL.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20260324075301_InitialCreateMySQL")]
    partial class InitialCreateMySQL
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Models.Bep", b =>
                {
                    b.Property<int>("IdBep")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdBep"));

                    b.Property<int?>("IdTrangThai")
                        .HasColumnType("int");

                    b.Property<string>("MaBep")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("MoTa")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("TenBep")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("IdBep");

                    b.ToTable("tbl_Bep", (string)null);
                });

            modelBuilder.Entity("Models.BienTheSanPham", b =>
                {
                    b.Property<int>("IdBienThe")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdBienThe"));

                    b.Property<double>("GiaBan")
                        .HasColumnType("double");

                    b.Property<int>("IdSanPham")
                        .HasColumnType("int");

                    b.Property<int?>("IdTrangThai")
                        .HasColumnType("int");

                    b.Property<string>("MaBienThe")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("MaSKU")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("TonKho")
                        .HasColumnType("int");

                    b.HasKey("IdBienThe");

                    b.ToTable("tbl_BienTheSanPham", (string)null);
                });

            modelBuilder.Entity("Models.BienTheThuocTinh", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("IdBienThe")
                        .HasColumnType("int");

                    b.Property<int>("IdGiaTri")
                        .HasColumnType("int");

                    b.Property<string>("MaBienTheThuocTinh")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("tbl_BienTheThuocTinh", (string)null);
                });

            modelBuilder.Entity("Models.ChiTietHoaDonBep", b =>
                {
                    b.Property<int>("IdChiTiet")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdChiTiet"));

                    b.Property<double>("GiaXuat")
                        .HasColumnType("double");

                    b.Property<int>("IdBienThe")
                        .HasColumnType("int");

                    b.Property<int>("IdHoaDon")
                        .HasColumnType("int");

                    b.Property<string>("MaChiTiet")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int");

                    b.Property<double>("ThanhTien")
                        .HasColumnType("double");

                    b.HasKey("IdChiTiet");

                    b.ToTable("tbl_ChiTietHoaDonBep", (string)null);
                });

            modelBuilder.Entity("Models.DanhMuc", b =>
                {
                    b.Property<int>("IdDanhMuc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdDanhMuc"));

                    b.Property<int?>("IdTrangThai")
                        .HasColumnType("int");

                    b.Property<string>("MaDanhMuc")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("TenDanhMuc")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("IdDanhMuc");

                    b.ToTable("tbl_DanhMuc", (string)null);
                });

            modelBuilder.Entity("Models.DanhMucLang", b =>
                {
                    b.Property<int>("IdDanhMuc")
                        .HasColumnType("int")
                        .HasColumnOrder(0);

                    b.Property<string>("MaNgonNgu")
                        .HasColumnType("varchar(255)")
                        .HasColumnOrder(1);

                    b.Property<string>("MoTa")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("TenDanhMuc")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("IdDanhMuc", "MaNgonNgu");

                    b.ToTable("tbl_DanhMuc_Lang", (string)null);
                });

            modelBuilder.Entity("Models.GiaTriThuocTinh", b =>
                {
                    b.Property<int>("IdGiaTri")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdGiaTri"));

                    b.Property<int>("IdThuocTinh")
                        .HasColumnType("int");

                    b.Property<string>("MaGiaTri")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("IdGiaTri");

                    b.ToTable("tbl_GiaTriThuocTinh", (string)null);
                });

            modelBuilder.Entity("Models.GiaTriThuocTinhLang", b =>
                {
                    b.Property<int>("IdGiaTri")
                        .HasColumnType("int")
                        .HasColumnOrder(0);

                    b.Property<string>("MaNgonNgu")
                        .HasColumnType("varchar(255)")
                        .HasColumnOrder(1);

                    b.Property<string>("GiaTri")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("IdGiaTri", "MaNgonNgu");

                    b.ToTable("tbl_GiaTriThuocTinh_Lang", (string)null);
                });

            modelBuilder.Entity("Models.HinhAnhSanPham", b =>
                {
                    b.Property<int>("IdHinhAnh")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdHinhAnh"));

                    b.Property<string>("DuongDanAnh")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int?>("IdBienThe")
                        .HasColumnType("int");

                    b.Property<int?>("IdSanPham")
                        .HasColumnType("int");

                    b.Property<bool>("LaAnhChinh")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("MaHinhAnh")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("ThuTu")
                        .HasColumnType("int");

                    b.HasKey("IdHinhAnh");

                    b.ToTable("tbl_HinhAnhSanPham", (string)null);
                });

            modelBuilder.Entity("Models.HoaDonBep", b =>
                {
                    b.Property<int>("IdHoaDon")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdHoaDon"));

                    b.Property<int>("IdBep")
                        .HasColumnType("int");

                    b.Property<int?>("IdTrangThai")
                        .HasColumnType("int");

                    b.Property<string>("MaHoaDon")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("NgayXuat")
                        .HasColumnType("datetime(6)");

                    b.Property<double>("TongTien")
                        .HasColumnType("double");

                    b.HasKey("IdHoaDon");

                    b.ToTable("tbl_HoaDonBep", (string)null);
                });

            modelBuilder.Entity("Models.LichSuDangNhap", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DiaChiIP")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("IdNguoiDung")
                        .HasColumnType("int");

                    b.Property<string>("ThietBi")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ThoiGian")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("tbl_LichSuDangNhap", (string)null);
                });

            modelBuilder.Entity("Models.LichSuGia", b =>
                {
                    b.Property<int>("IdLichSu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdLichSu"));

                    b.Property<double?>("GiaCu")
                        .HasColumnType("double");

                    b.Property<double?>("GiaMoi")
                        .HasColumnType("double");

                    b.Property<int>("IdBienThe")
                        .HasColumnType("int");

                    b.Property<string>("MaLichSu")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("NgayThayDoi")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("IdLichSu");

                    b.ToTable("tbl_LichSuGia", (string)null);
                });

            modelBuilder.Entity("Models.LoaiTrangThai", b =>
                {
                    b.Property<int>("IdLoaiTrangThai")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdLoaiTrangThai"));

                    b.Property<string>("MaLoaiTrangThai")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("MoTa")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("TenLoaiTrangThai")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("IdLoaiTrangThai");

                    b.ToTable("tbl_LoaiTrangThai", (string)null);
                });

            modelBuilder.Entity("Models.NgonNgu", b =>
                {
                    b.Property<string>("MaNgonNgu")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("KyHieuTienTe")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("LaMacDinh")
                        .HasColumnType("int");

                    b.Property<DateTime?>("NgayCapNhat")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("TenNgonNgu")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("TiGiaDoiToai")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("MaNgonNgu");

                    b.ToTable("tbl_NgonNgu", (string)null);
                });

            modelBuilder.Entity("Models.NguoiDung", b =>
                {
                    b.Property<int>("IdNguoiDung")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdNguoiDung"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int?>("IdTrangThai")
                        .HasColumnType("int");

                    b.Property<DateTime?>("LanDangNhapCuoi")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("MaNguoiDung")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("MatKhau")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("SoDienThoai")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("TenDangNhap")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("IdNguoiDung");

                    b.ToTable("tbl_NguoiDung", (string)null);
                });

            modelBuilder.Entity("Models.NguoiDungVaiTro", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("IdNguoiDung")
                        .HasColumnType("int");

                    b.Property<int>("IdVaiTro")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("tbl_NguoiDungVaiTro", (string)null);
                });

            modelBuilder.Entity("Models.NhatKyHeThong", b =>
                {
                    b.Property<int>("IdNhatKy")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdNhatKy"));

                    b.Property<string>("HanhDong")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("IdNguoiDung")
                        .HasColumnType("int");

                    b.Property<string>("MaNhatKy")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ThoiGian")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("IdNhatKy");

                    b.ToTable("tbl_NhatKyHeThong", (string)null);
                });

            modelBuilder.Entity("Models.Quyen", b =>
                {
                    b.Property<int>("IdQuyen")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdQuyen"));

                    b.Property<string>("MaQuyen")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("MoTa")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("TenQuyen")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("IdQuyen");

                    b.ToTable("tbl_Quyen", (string)null);
                });

            modelBuilder.Entity("Models.SanPham", b =>
                {
                    b.Property<int>("IdSanPham")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdSanPham"));

                    b.Property<int?>("IdDanhMuc")
                        .HasColumnType("int");

                    b.Property<int?>("IdTrangThai")
                        .HasColumnType("int");

                    b.Property<string>("MaSanPham")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime(6)");

                    b.HasKey("IdSanPham");

                    b.ToTable("tbl_SanPham", (string)null);
                });

            modelBuilder.Entity("Models.SanPhamLang", b =>
                {
                    b.Property<int>("IdSanPham")
                        .HasColumnType("int")
                        .HasColumnOrder(0);

                    b.Property<string>("MaNgonNgu")
                        .HasColumnType("varchar(255)")
                        .HasColumnOrder(1);

                    b.Property<string>("MoTa")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("TenSanPham")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("IdSanPham", "MaNgonNgu");

                    b.ToTable("tbl_SanPham_Lang", (string)null);
                });

            modelBuilder.Entity("Models.ThongTinNguoiDung", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AnhDaiDien")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("DiaChi")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("GioiTinh")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("IdNguoiDung")
                        .HasColumnType("int");

                    b.Property<string>("NgaySinh")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("tbl_ThongTinNguoiDung", (string)null);
                });

            modelBuilder.Entity("Models.ThuocTinh", b =>
                {
                    b.Property<int>("IdThuocTinh")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdThuocTinh"));

                    b.Property<string>("MaThuocTinh")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("IdThuocTinh");

                    b.ToTable("tbl_ThuocTinh", (string)null);
                });

            modelBuilder.Entity("Models.ThuocTinhLang", b =>
                {
                    b.Property<int>("IdThuocTinh")
                        .HasColumnType("int");

                    b.Property<string>("MaNgonNgu")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("TenThuocTinh")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("IdThuocTinh", "MaNgonNgu");

                    b.ToTable("tbl_ThuocTinh_Lang", (string)null);
                });

            modelBuilder.Entity("Models.TrangThai", b =>
                {
                    b.Property<int>("IdTrangThai")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdTrangThai"));

                    b.Property<int?>("IdLoaiTrangThai")
                        .HasColumnType("int");

                    b.Property<string>("MaTrangThai")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("MoTa")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("TenTrangThai")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("IdTrangThai");

                    b.ToTable("tbl_TrangThai", (string)null);
                });

            modelBuilder.Entity("Models.VaiTro", b =>
                {
                    b.Property<int>("IdVaiTro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdVaiTro"));

                    b.Property<string>("MaVaiTro")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("MoTa")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("TenVaiTro")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("IdVaiTro");

                    b.ToTable("tbl_VaiTro", (string)null);
                });

            modelBuilder.Entity("Models.VaiTroQuyen", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("IdQuyen")
                        .HasColumnType("int");

                    b.Property<int>("IdVaiTro")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("tbl_VaiTroQuyen", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
